// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: channels.sql

package database

import (
	"context"

	ulid "github.com/oklog/ulid/v2"
)

const createChannel = `-- name: CreateChannel :exec
INSERT INTO channels (server_id, channel_id, name, type, created_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateChannelParams struct {
	ServerID  ulid.ULID `json:"server_id"`
	ChannelID ulid.ULID `json:"channel_id"`
	Name      string    `json:"name"`
	Type      string    `json:"type"`
	CreatedAt int64     `json:"created_at"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) error {
	_, err := q.db.ExecContext(ctx, createChannel,
		arg.ServerID,
		arg.ChannelID,
		arg.Name,
		arg.Type,
		arg.CreatedAt,
	)
	return err
}

const getChannel = `-- name: GetChannel :one
SELECT server_id, channel_id, name, type, created_at FROM channels
WHERE server_id = ? AND channel_id = ?
`

type GetChannelParams struct {
	ServerID  ulid.ULID `json:"server_id"`
	ChannelID ulid.ULID `json:"channel_id"`
}

func (q *Queries) GetChannel(ctx context.Context, arg GetChannelParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, getChannel, arg.ServerID, arg.ChannelID)
	var i Channel
	err := row.Scan(
		&i.ServerID,
		&i.ChannelID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const listChannels = `-- name: ListChannels :many
SELECT server_id, channel_id, name, type, created_at FROM channels
WHERE server_id = ? AND channel_id > ? LIMIT ?
`

type ListChannelsParams struct {
	ServerID  ulid.ULID `json:"server_id"`
	ChannelID ulid.ULID `json:"channel_id"`
	Limit     int64     `json:"limit"`
}

func (q *Queries) ListChannels(ctx context.Context, arg ListChannelsParams) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, listChannels, arg.ServerID, arg.ChannelID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ServerID,
			&i.ChannelID,
			&i.Name,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelsAll = `-- name: ListChannelsAll :many
SELECT server_id, channel_id, name, type, created_at FROM channels WHERE server_id = ?
`

func (q *Queries) ListChannelsAll(ctx context.Context, serverID ulid.ULID) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, listChannelsAll, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ServerID,
			&i.ChannelID,
			&i.Name,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChannel = `-- name: UpdateChannel :exec
UPDATE channels
SET name = ?, type = ?
WHERE server_id = ? AND channel_id = ?
`

type UpdateChannelParams struct {
	Name      string    `json:"name"`
	Type      string    `json:"type"`
	ServerID  ulid.ULID `json:"server_id"`
	ChannelID ulid.ULID `json:"channel_id"`
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) error {
	_, err := q.db.ExecContext(ctx, updateChannel,
		arg.Name,
		arg.Type,
		arg.ServerID,
		arg.ChannelID,
	)
	return err
}
