// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: channels.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	ulid "github.com/oklog/ulid/v2"
)

const createChannel = `-- name: CreateChannel :exec
INSERT INTO channels (channel_id, name, type, created_at)
VALUES ($1, $2, $3, $4)
`

type CreateChannelParams struct {
	ChannelID ulid.ULID        `json:"channel_id"`
	Name      string           `json:"name"`
	Type      string           `json:"type"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) error {
	_, err := q.db.Exec(ctx, createChannel,
		arg.ChannelID,
		arg.Name,
		arg.Type,
		arg.CreatedAt,
	)
	return err
}

const getChannel = `-- name: GetChannel :one
SELECT channel_id, name, type, created_at FROM channels
WHERE channel_id = $1
`

func (q *Queries) GetChannel(ctx context.Context, channelID ulid.ULID) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannel, channelID)
	var i Channel
	err := row.Scan(
		&i.ChannelID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const listChannels = `-- name: ListChannels :many
SELECT channel_id, name, type, created_at FROM channels
WHERE channel_id > $1 LIMIT $2
`

type ListChannelsParams struct {
	ChannelID ulid.ULID `json:"channel_id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListChannels(ctx context.Context, arg ListChannelsParams) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listChannels, arg.ChannelID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ChannelID,
			&i.Name,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelsAll = `-- name: ListChannelsAll :many
SELECT channel_id, name, type, created_at FROM channels
`

func (q *Queries) ListChannelsAll(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listChannelsAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ChannelID,
			&i.Name,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
